### ISSUE TITLE
Enable lint directives

### ISSUE THREAD

**Issue by skymandr** [Scan-o-Matic/scanomatic-standalone#133]
# 📋 Info

We currently disable the following lint directives in `.eslintrc.yml`:
```yaml
  import/extensions: "off"
  import/no-extraneous-dependencies: "off"
  jsx-a11y/label-has-for: "off"
  jsx-a11y/label-has-associated-control: "off"
  react/jsx-props-no-spreading: "off"
  react/destructuring-assignment: "off"
  no-promise-executor-return: "off"
```
of these at least
```yaml
  import/no-extraneous-dependencies: "off"
  react/jsx-props-no-spreading: "off"
  react/destructuring-assignment: "off"
  no-promise-executor-return: "off"
```
should probably be active. Note, however, that activating them all will give 400+ new lint errors to deal with.

Some comments:
- `no-extraneous-dependencies`: The problem is only with `enzyme-setup.js`, which the linter doesn't understand is part of the dev environment. I think it happens because test files are located in the same directory structure as the compoenents. Moving the tests could probably solve this, or telling the linter something to let it understand that the `test` directory is not part of the main project as such.
- `jsx-props-no-spreading` This is typically that we do `{...props}` in tests. The straightforward solution is to replace this with all the component arguments instead, which is extremely tedious, since there are 200+ instances of this.
- `destructuring-assignment`: This is typically that we assign using `props.value` or similar. Easy to fix, but another 200+
- `no-promise-executor-return`: All four instances of this happen in `api.js`. I'm not sure how to fix this.

# 🏁 DoD

- [ ] The lint directives we want are active
- [ ] The code is lint-free
